// <auto-generated />
namespace cmc2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateGroupW2CmcMembers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateGroupW2CmcMembers));
        
        string IMigrationMetadata.Id
        {
            get { return "201803211508025_updateGroupW2CmcMembers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
